# Site settings
name: Kishore K Poluri
email: kishorekpoluri@gmail.com
#canonical_url: https://edwinexemplar.com
keywords: "Software Engineer (Full Stack), Java,SQL Development, Ember JS, React, Angular, Spring Boot, MicroServices, Jersey, Hibernate, Oracle, Teradata, Agile, Pair Programming"
skills: "Software Engineer (Full Stack) in Detroit, MI"
baseurl:

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
# You should replace these with your social networks, of course. :)
social:
  - title: linkedin
    url: https://www.linkedin.com/in/kishore-k-poluri/
  - title: medium
    url: https://medium.com/@kishorek.poluri
  - title: twitter
    url: https://twitter.com/kkppkk123
    
# Google webmaster tools
google_verify:

# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 2196F3
  primary-rgb: "33, 150, 243"
  secondary: 285172
  secondary-dark: 29455b
  section-tout: eaf1f1



# Build settings
markdown: kramdown
permalink: pretty
